apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-demo
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: simple-demo
spec:
  env:
    - name: SIMPLE_API_URL
      value: http://simple-api:8080
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/mathesonbr/simple-demo.git
      ref:
        branch: main
